## ASS 2 : Build a Text Preprocessing Pipeline

## Part 1 — Collect Data (Wikipedia Scraping)

## Selecting 4 Categories:
- Artificial Intelligence
- Climate Change
- Space Exploration
- World History

## For each category, scrape at least 15 Wikipedia articles
## Extract only the main text (ignore references, links, etc.)

### Importing Libraries

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [5]:
import requests

url = "https://en.wikipedia.org/wiki/Artificial_intelligence"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
}

response = requests.get(url, headers=headers)

print(response.status_code)

200

## Choosing 4 categories

In [6]:
categories = {
    "AI": [
        "Artificial_intelligence",
        "Machine_learning",
        "Deep_learning",
        "Neural_network",
        "Computer_vision",
        "Natural_language_processing",
        "Expert_system",
        "Data_mining",
        "Generative_artificial_intelligence",
        "Reinforcement_learning",
        "Chatbot",
        "Speech_recognition",
        "Knowledge_representation_and_reasoning",
        "Artificial_general_intelligence",
        "Robotics"
    ],

    "Climate": [
        "Climate_change",
        "Global_warming",
        "Greenhouse_effect",
        "Carbon_dioxide",
        "Renewable_energy",
        "Deforestation",
        "Sustainability",
        "Kyoto_Protocol",
        "Paris_Agreement",
        "Sea_level_rise",
        "Carbon_footprint",
        "Environmentalism",
        "Climate_model",
        "Extreme_weather",
        "Solar_energy"
    ],

    "Space": [
        "Space_exploration",
        "Mars",
        "Moon",
        "NASA",
        "International_Space_Station",
        "Apollo_program",
        "Space_Shuttle",
        "SpaceX",
        "Rocket",
        "Voyager_program",
        "Hubble_Space_Telescope",
        "Mars_rover",
        "Satellite",
        "Astronaut",
        "James_Webb_Space_Telescope"
    ],

    "History": [
        "World_History",
        "Ancient_Egypt",
        "Ancient_Greece",
        "Roman_Empire",
        "Middle_Ages",
        "French_Revolution",
        "Industrial_Revolution",
        "World_War_I",
        "World_War_II",
        "Renaissance",
        "Cold_War",
        "Mongol_Empire",
        "Ottoman_Empire",
        "History_of_China",
        "History_of_India"
    ]
}

## Creating Function to Scrape Wikipedia

In [7]:
def scrape_wikipedia(article):
    url = f"https://en.wikipedia.org/wiki/{article}"

    response = requests.get(
        url,
        headers={"User-Agent": "Mozilla/5.0"}
    )

    soup = BeautifulSoup(response.text, "html.parser")

    paragraphs = soup.find_all("p")

    text = " ".join(
        p.get_text(strip=True)
        for p in paragraphs
    )

    return text

## collecting data

In [9]:
import pandas as pd
import time

dataset = []

for label, articles in categories.items():

    print(f"\nCollecting {label} articles...")

    for article in articles:

        try:
            text = scrape_wikipedia(article)

            dataset.append({
                "Text": text,
                "Label": label
            })

            print("Done:", article)

            time.sleep(1)

        except Exception as e:
            print("Error:", article, e)

Collecting AI articles...
Done: Artificial_intelligence
Done: Machine_learning
Done: Deep_learning
Done: Neural_network
Done: Computer_vision
Done: Natural_language_processing
Done: Expert_system
Done: Data_mining
Done: Generative_artificial_intelligence
Done: Reinforcement_learning
Done: Chatbot
Done: Speech_recognition
Done: Knowledge_representation_and_reasoning
Done: Artificial_general_intelligence
Done: Robotics

Collecting Climate articles...
Done: Climate_change
Done: Global_warming
Done: Greenhouse_effect
Done: Carbon_dioxide
Done: Renewable_energy
Done: Deforestation
Done: Sustainability
Done: Kyoto_Protocol
Done: Paris_Agreement
Done: Sea_level_rise
Done: Carbon_footprint
Done: Environmentalism
Done: Climate_model
Done: Extreme_weather
Done: Solar_energy

Collecting Space articles...
Done: Space_exploration
Done: Mars
Done: Moon
Done: NASA
Done: International_Space_Station
Done: Apollo_program
Done: Space_Shuttle
Done: SpaceX
Done: Rocket
Done: Voyager_program
Done: Hubble_Space_Telescope
Done: Mars_rover
Done: Satellite
Done: Astronaut
Done: James_Webb_Space_Telescope

Collecting History articles...
Done: World_History
Done: Ancient_Egypt
Done: Ancient_Greece
Done: Roman_Empire
Done: Middle_Ages
Done: French_Revolution
Done: Industrial_Revolution
Done: World_War_I
Done: World_War_II
Done: Renaissance
Done: Cold_War
Done: Mongol_Empire
Done: Ottoman_Empire
Done: History_of_China
Done: History_of_India

## checking whether data is collected or not

In [10]:
print("Total articles collected:", len(dataset))

Total articles collected: 60

## Inspecting first article

In [11]:
print(dataset[0]["Label"])
print(dataset[0]["Text"][:500])

AI
 Artificial intelligence(AI) is the capability ofcomputational systemsto perform tasks typically associated withhuman intelligence, such aslearning,reasoning,problem-solving,perception, anddecision-making. It is afield of researchinengineering,mathematicsandcomputer sciencethat develops and studies methods andsoftwarethat enable machines to perceive their environment and uselearningandintelligenceto take actions that maximize their chances of achieving defined goals.[1] High-profileapplications

## converting to dataframe

In [12]:
df = pd.DataFrame(dataset)

print(df.shape)

df.head()

(60, 2)

                                                Text Label
0   Artificial intelligence(AI) is the capability...    AI
1   Machine learning(ML) is a field of study inar...    AI
2  Inmachine learning,deep learning(DL) focuses o...    AI
3  Aneural networkis a group of interconnected un...    AI
4  Computer visiontasks include methods foracquir...    AI

## checking article length

In [13]:
for item in dataset[:5]:
    print(item["Label"], len(item["Text"]))

AI 84544
AI 57872
AI 54975
AI 4774
AI 25127

In [14]:
## checking total counts of each category.

In [15]:
print(df["Label"].value_counts())

Label
AI         15
Climate    15
Space      15
History    15
Name: count, dtype: int64

In [16]:
print(df.head())

                                                Text Label
0   Artificial intelligence(AI) is the capability...    AI
1   Machine learning(ML) is a field of study inar...    AI
2  Inmachine learning,deep learning(DL) focuses o...    AI
3  Aneural networkis a group of interconnected un...    AI
4  Computer visiontasks include methods foracquir...    AI

In [17]:
df.to_csv("wikipedia.csv",
          index=False,      # Don't save row numbers/index
          encoding="utf-8"  # Save text in UTF-8 format
)

## Part 2 — Clean the Text

## Applying these steps-
- Remove HTML tags
- Remove citations like [1], [23]
- Remove punctuation/special characters
- Convert text to lowercase
- Remove extra spaces

## 1.Load the dataset

In [18]:
import pandas as pd

df = pd.read_csv("wikipedia.csv")
print(df.head())

                                                Text Label
0   Artificial intelligence(AI) is the capability...    AI
1   Machine learning(ML) is a field of study inar...    AI
2  Inmachine learning,deep learning(DL) focuses o...    AI
3  Aneural networkis a group of interconnected un...    AI
4  Computer visiontasks include methods foracquir...    AI

In [19]:
## sample Text
sample_text = df["Text"][0]

print(sample_text[:500])

 Artificial intelligence(AI) is the capability ofcomputational systemsto perform tasks typically associated withhuman intelligence, such aslearning,reasoning,problem-solving,perception, anddecision-making. It is afield of researchinengineering,mathematicsandcomputer sciencethat develops and studies methods andsoftwarethat enable machines to perceive their environment and uselearningandintelligenceto take actions that maximize their chances of achieving defined goals.[1] High-profileapplications

## Remove HTML Tags

In [20]:
import re
## function
def remove_html(text):
    return re.sub(r'<.*?>', '', str(text))

In [21]:
df["Text"] = df["Text"].apply(remove_html) ## apply to dataset

In [22]:
## eg.
example = ("<p>I am doing study right now <b>python</b></p>")

print("Before:",example)
print("After removing HTML Tag:",remove_html(example))

Before: <p>I am doing study right now <b>python</b></p>
After removing HTML Tag: I am doing study right now python

## Remove citations like [1], [23]

In [23]:
## func
def remove_citations(text):
    return re.sub(r'\[\d+\]', '', text)

In [24]:
## e.g.
example = "Artificial Intelligence is important [1] and useful [23][50]."

print("Before:",example)
print("After removing citations:",remove_citations(example))

Before: Artificial Intelligence is important [1] and useful [23][50].
After removing citations: Artificial Intelligence is important  and useful .

## Remove punctuation/special characters

In [25]:
## func
def remove_punctuation(text):
    return re.sub(r'[^a-zA-Z0-9\s]', '', text)

In [26]:
## e.g.
example = "Wow!!! Are you sure this works @ 100% — because I just tested it & it returned: Success  (time: 12:30 PM, cost: $0.00)."

print("Before:",example)
print("After removing punctuations/ Special Characters:",remove_punctuation(example))

Before: Wow!!! Are you sure this works @ 100% — because I just tested it & it returned: Success  (time: 12:30 PM, cost: $0.00).
After removing punctuations/ Special Characters: Wow Are you sure this works  100  because I just tested it  it returned Success  time 1230 PM cost 000

## Convert text to lowercase

In [27]:
def convert_lowercase(text):
    return text.lower()

In [28]:
example = "Artificial Intelligence and Machine Learning is very Important"

print("Before:",example)
print("After converting to lowercase:",convert_lowercase(example))

Before: Artificial Intelligence and Machine Learning is very Important
After converting to lowercase: artificial intelligence and machine learning is very important

## Remove extra spaces

In [29]:
def remove_extra_spaces(text):
    return re.sub(r'\s+', ' ', text).strip()

In [30]:
example = "artificial     intelligence      is powerful"

print("Before:",example)
print("After removing space:",remove_extra_spaces(example))

Before: artificial     intelligence      is powerful
After removing space: artificial intelligence is powerful

In [31]:
## original data
original_df = pd.read_csv("wikipedia.csv")

In [32]:
print("BEFORE:",original_df["Text"][0][:1000])

print("\n" + "="*50 + "\n")

print("AFTER:",df["Text"][0][:1000])

BEFORE:  Artificial intelligence(AI) is the capability ofcomputational systemsto perform tasks typically associated withhuman intelligence, such aslearning,reasoning,problem-solving,perception, anddecision-making. It is afield of researchinengineering,mathematicsandcomputer sciencethat develops and studies methods andsoftwarethat enable machines to perceive their environment and uselearningandintelligenceto take actions that maximize their chances of achieving defined goals.[1] High-profileapplications of AIinclude advancedweb search engines,chatbots,virtual assistants,autonomous vehicles, and play and analysis instrategy games(e.g.,chessandGo). Since the 2020s,generative AIhas become widely available to generate images, audio, and videos from text prompts. The traditional goals of AI research include learning,reasoning,knowledge representation,planning,natural language processing, andperception, as well as support forrobotics.[a]To reach these goals, AI researchers have used techniques includ

==================================================

AFTER:  Artificial intelligence(AI) is the capability ofcomputational systemsto perform tasks typically associated withhuman intelligence, such aslearning,reasoning,problem-solving,perception, anddecision-making. It is afield of researchinengineering,mathematicsandcomputer sciencethat develops and studies methods andsoftwarethat enable machines to perceive their environment and uselearningandintelligenceto take actions that maximize their chances of achieving defined goals.[1] High-profileapplications of AIinclude advancedweb search engines,chatbots,virtual assistants,autonomous vehicles, and play and analysis instrategy games(e.g.,chessandGo). Since the 2020s,generative AIhas become widely available to generate images, audio, and videos from text prompts. The traditional goals of AI research include learning,reasoning,knowledge representation,planning,natural language processing, andperception, as well as support forrobotics.[a]To reach these goals, AI researchers have used techniques includ

In [33]:
## verifying
df.head()

                                                Text Label
0   Artificial intelligence(AI) is the capability...    AI
1   Machine learning(ML) is a field of study inar...    AI
2  Inmachine learning,deep learning(DL) focuses o...    AI
3  Aneural networkis a group of interconnected un...    AI
4  Computer visiontasks include methods foracquir...    AI

## Save cleaned dataset

In [34]:
df.to_csv("cleaned_dataset.csv",index=False,encoding="utf-8")
print("Data saved successfully")

Data saved successfully

In [ ]:
## flow 
raw_dataset.csv
       ↓
Remove HTML tags
       ↓
Remove citations
       ↓
Remove punctuation
       ↓
Lowercase
       ↓
Remove extra spaces
       ↓
cleaned_dataset.csv

## Part 3 — NLP Preprocessing

## Step 1: Tokenisation
- Split text into words using nltk.word_tokenize()
- Add a new column: tokens
## Show first 20 tokens of one article

## 1. Importing nltk and download tokenizer

In [1]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

## 2.Import tokenizer

In [2]:
from nltk.tokenize import word_tokenize

## 3.creating new column tokens

In [36]:
df['tokens'] = df['Text'].apply(word_tokenize)

## 4.Displaying one article and its tokens

In [38]:
print("Original Article:", df['Text'].iloc[0])

print("First 20 Tokens:",df['tokens'].iloc[0][:20])

Original Article:  Artificial intelligence(AI) is the capability ofcomputational systemsto perform tasks typically associated withhuman intelligence, such aslearning,reasoning,problem-solving,perception, anddecision-making. It is afield of researchinengineering,mathematicsandcomputer sciencethat develops and studies methods andsoftwarethat enable machines to perceive their environment and uselearningandintelligenceto take actions that maximize their chances of achieving defined goals.[1] High-profileapplications of AIinclude advancedweb search engines,chatbots,virtual assistants,autonomous vehicles, and play and analysis instrategy games(e.g.,chessandGo). Since the 2020s,generative AIhas become widely available to generate images, audio, and videos from text prompts. The traditional goals of AI research include learning,reasoning,knowledge representation,planning,natural language processing, andperception, as well as support forrobotics.[a]To reach these goals, AI researchers have used techniques includingstate space searchandmathematical optimization,formal logic,artificial neural networks, and methods based onstatistics,operations research, andeconomics.[b]AI also draws uponpsychology,linguistics,philosophy,neuroscience, and other fields.[2]Some companies, such asOpenAI,Google DeepMindandMeta, aim to createartificial general intelligence(AGI) – AI that can complete virtually any cognitive task at least as well as a human.[3] Artificial intelligence was founded as an academic discipline in 1956,[4]and the field went through multiple cycles of optimism throughoutits history,[5][6]followed by periods of disappointment and loss of funding, known asAI winters.[7][8]Funding and interest increased substantially after 2012, whengraphics processing unitsbegan being used to accelerate neural networks, anddeep learningoutperformed previous AI techniques.[9]This growth accelerated further after 2017 with thetransformer architecture.[10]In the 2020s, anAI boomhas coincided with advances ingenerative AI, which allowed for the creation and modification of media. In addition toAI safetyandunintended consequences and harmsfrom the use of AI,ethical concerns,AI's long-term effects, andpotential existential riskshave prompted discussions ofAI regulation. The general problem of simulating (or creating) intelligence has been broken into subproblems. These consist of particular traits or capabilities that researchers expect an intelligent system to display. The traits described below have received the most attention and cover the scope of AI research.[a] Early researchers developed algorithms that imitated step-by-step reasoning that humans use when they solve puzzles or make logicaldeductions.[11]By the late 1980s and 1990s, methods were developed for dealing withuncertainor incomplete information, employing concepts fromprobabilityandeconomics.[12] Many of thesealgorithmsare insufficient for solving large reasoning problems because they experience a "combinatorial explosion": They become exponentially slower as the problems grow.[13]Even humans rarely use the step-by-step deduction that early AI research could model. They solve most of their problems using fast, intuitive judgments.[14]Accurate and efficient reasoning is an unsolved problem. Knowledge representationandknowledge engineering[15]allow AI programs to answer questions intelligently and make deductions about real-world facts. Formal knowledge representations are used in content-based indexing and retrieval,[16]scene interpretation,[17]clinical decision support,[18]knowledge discovery (mining "interesting" and actionable inferences from largedatabases),[19]and other areas.[20] Aknowledge baseis a body of knowledge represented in a form that can be used by a program. Anontologyis the set of objects, relations, concepts, and properties used by a particular domain of knowledge.[21]Knowledge bases need to represent things such as objects, properties, categories, and relations between objects;[22]situations, events, states, and time;[23]causes and effects;[24]knowledge about knowledge (what we know about what other people know);[25]default reasoning(things that humans assume are true until they are told differently and will remain true even when other facts are changing);[26]and many other aspects and domains of knowledge. Among the most difficult problems in knowledge representation are the breadth ofcommonsense knowledge(the set of atomic facts that the average person knows is enormous);[27]and the sub-symbolic form of most commonsense knowledge (much of what people know is not represented as "facts" or "statements" that they could express verbally).[14]There is also the difficulty ofknowledge acquisition, the problem of obtaining knowledge for AI applications.[c] An "agent" is any entity (artificial or not) that perceives and takes actions in the world. Arational agenthas goals or preferences and takes actions to make them happen.[d][30]Inautomated planning, the agent has a specific goal.[31]Inautomated decision-making, the agent has preferences—there are some situations it would prefer to be in, and some situations it is trying to avoid. The decision-making agent assigns a number to each situation (called the "utility") that measures how much the agent prefers it. For each possible action, it can calculate the "expected utility": the utility of all possible outcomes of the action, weighted by the probability that the outcome will occur. It can then choose the action with the maximum expected utility.[32] Inclassical planning, the agent knows exactly what the effect of any action will be.[33]In most real-world problems, however, the agent may not be certain about the situation they are in (it is "unknown" or "unobservable") and it may not know for certain what will happen after each possible action (it is not "deterministic"). It must choose an action by making a probabilistic guess and then reassess the situation to see if the action worked.[34] Alongside thorough testing and improvement based on previous decisions, having an explanation for why the agent took certain decisions is a way to build trust, especially when the decisions have to be relied upon.[35] In some problems, the agent's preferences may be uncertain, especially if there are other agents or humans involved. These can be learned (e.g., withinverse reinforcement learning), or the agent can seek information to improve its preferences.[36]Information value theorycan be used to weigh the value of exploratory or experimental actions.[37]The space of possible future actions and situations is typicallyintractablylarge, so the agents must take actions and evaluate situations while being uncertain of what the outcome will be. AMarkov decision processhas atransition modelthat describes the probability that a particular action will change the state in a particular way and a reward function that supplies the utility of each state and the cost of each action. Apolicyassociates a decision with each possible state. The policy could be calculated (e.g., byiteration), beheuristic, or it can be learned.[38] Game theorydescribes the rational behavior of multiple interacting agents and is used in AI programs that make decisions that involve other agents.[39] Machine learningis the study of programs that can improve their performance on a given task automatically.[40]It has been a part of AI from the beginning.[e] There are several kinds of machine learning.Unsupervised learninganalyzes a stream of data and finds patterns and makes predictions without any other guidance.[43]Supervised learningrequires labeling the training data with the expected answers, and comes in two main varieties:classification(where the program must learn to predict what category the input belongs in) andregression(where the program must deduce a numeric function based on numeric input).[44] Inreinforcement learning, the agent is rewarded for good responses and punished for bad ones. The agent learns to choose responses that are classified as "good".[45]Transfer learningis when the knowledge gained from one problem is applied to a new problem.[46]Deep learningis a type of machine learning that runs inputs through biologically inspiredartificial neural networksfor all of these types of learning.[47] Computational learning theorycan assess learners bycomputational complexity, bysample complexity(how much data is required), or by other notions ofoptimization.[48] Natural language processing(NLP) allows programs to read, write and communicate in human languages.[49]Specific problems includespeech recognition,speech synthesis,machine translation,information extraction,information retrievalandquestion answering.[50] Early work, based onNoam Chomsky'sgenerative grammarandsemantic networks, had difficulty withword-sense disambiguation[f]unless restricted to small domains called "micro-worlds" (due to thecommon sense knowledge problem[27]).Margaret Mastermanbelieved that it was meaning and not grammar that was the key to understanding languages, and thatthesauriand not dictionaries should be the basis of computational language structure. Modern deep learning techniques for NLP includeword embedding(representing words, typically asvectorsencoding their meaning),[51]transformers(a deep learning architecture using anattentionmechanism),[52]and others.[53]In 2019,generative pre-trained transformer(or "GPT") language models began to generate coherent text,[54][55]and by 2023, these models were able to get human-level scores on thebar exam,SATtest,GREtest, and many other real-world applications.[56] Machine perceptionis the ability to use input from sensors (such as cameras, microphones, wireless signals, activelidar, sonar, radar, andtactile sensors) to deduce aspects of the world.Computer visionis the ability to analyze visual input.[57] The field includesspeech recognition,[58]image classification,[59]facial recognition,object recognition,[60]object tracking,[61]androbotic perception.[62] Affective computingis a field that comprises systems that recognize, interpret, process, or simulate humanfeeling, emotion, and mood.[64]For example, somevirtual assistantsare programmed to speak conversationally or even to banter humorously; it makes them appear more sensitive to the emotional dynamics of human interaction, or to otherwise facilitatehuman–computer interaction. However, this tends to give naïve users an unrealistic conception of the intelligence of existing computer agents.[65]Moderate successes related to affective computing include textualsentiment analysisand, more recently,multimodal sentiment analysis, wherein AI classifies the effects displayed by a videotaped subject.[66] A machine withartificial general intelligencewould be able to solve a wide variety of problems with breadth and versatility similar tohuman intelligence.[67] AI research uses a wide variety of techniques to accomplish the goals above.[b] There are two different kinds of search used in AI:state space searchandlocal search: State space searchsearches through a tree of possible states to try to find a goal state.[68]For example,planningalgorithms search through trees of goals and subgoals, attempting to find a path to a target goal, a process calledmeans-ends analysis.[69] Simple exhaustive searches[70]are rarely sufficient for most real-world problems: thesearch space(the number of places to search) quickly grows toastronomical numbers. The result is a search that istoo slowor never completes.[13]"Heuristics" or "rules of thumb" can help prioritize choices that are more likely to reach a goal.[71] Adversarial searchis used forgame-playingprograms, such as chess or Go. It searches through atreeof possible moves and countermoves, looking for a winning position.[72] Local searchusesmathematical optimizationto find a solution to a problem. It begins with some form of guess and refines it incrementally.[73] Gradient descentis a type of local search that optimizes a set of numerical parameters by incrementally adjusting them to minimize aloss function. Variants of gradient descent are commonly used to trainneural networks,[74]through thebackpropagationalgorithm. Another type of local search isevolutionary computation, which aims to iteratively improve a set of candidate solutions by "mutating" and "recombining" them,selectingonly the fittest to survive each generation.[75] Distributed search processes can coordinate viaswarm intelligencealgorithms. Two popular swarm algorithms used in search areparticle swarm optimization(inspired by birdflocking) andant colony optimization(inspired byant trails).[76] Formallogicis used forreasoningandknowledge representation.[77]Formal logic comes in two main forms:propositional logic(which operates on statements that are true or false and useslogical connectivessuch as "and", "or", "not" and "implies")[78]andpredicate logic(which also operates on objects, predicates and relations and usesquantifierssuch as "EveryXis aY" and "There aresomeXs that areYs").[79] Deductive reasoningin logic is the process ofprovinga new statement (conclusion) from other statements that are given and assumed to be true (thepremises).[80]Proofs can be structured as prooftrees, in which nodes are labelled by sentences, and children nodes are connected to parent nodes byinference rules. Given a problem and a set of premises, problem-solving reduces to searching for a proof tree whose root node is labelled by a solution of the problem and whoseleaf nodesare labelled by premises oraxioms. In the case ofHorn clauses, problem-solving search can be performed by reasoningforwardsfrom the premises orbackwardsfrom the problem.[81]In the more general case of the clausal form offirst-order logic,resolutionis a single, axiom-free rule of inference, in which a problem is solved by proving a contradiction from premises that include the negation of the problem to be solved.[82] Inference in both Horn clause logic and first-order logic isundecidable, and thereforeintractable. However, backward reasoning with Horn clauses, which underpins computation in thelogic programminglanguageProlog, isTuring complete. Moreover, its efficiency is competitive with computation in othersymbolic programminglanguages.[83] Fuzzy logicassigns a "degree of truth" between 0 and 1. It can therefore handle propositions that are vague and partially true.[84] Non-monotonic logics, including logic programming withnegation as failure, are designed to handledefault reasoning.[26]Other specialized versions of logic have been developed to describe many complex domains. Many problems in AI (including reasoning, planning, learning, perception, and robotics) require the agent to operate with incomplete or uncertain information. AI researchers have devised a number of tools to solve these problems using methods fromprobabilitytheory and economics.[85]Precise mathematical tools have been developed that analyze how an agent can make choices and plan, usingdecision theory,decision analysis,[86]andinformation value theory.[87]These tools include models such asMarkov decision processes,[88]dynamicdecision networks,[89]game theoryandmechanism design.[90] Bayesian networks[91]are a tool that can be used forreasoning(using theBayesian inferencealgorithm),[g][93]learning(using theexpectation–maximization algorithm),[h][95]planning(usingdecision networks)[96]andperception(usingdynamic Bayesian networks).[89] Probabilistic algorithms can also be used for filtering, prediction, smoothing, and finding explanations for streams of data, thus helping perception systems analyze processes that occur over time (e.g.,hidden Markov modelsorKalman filters).[89] The simplest AI applications can be divided into two types: classifiers (e.g., "if shiny then diamond"), on one hand, and controllers (e.g., "if diamond then pick up"), on the other hand.Classifiers[97]are functions that usepattern matchingto determine the closest match. They can be fine-tuned based on chosen examples usingsupervised learning. Each pattern (also called an "observation") is labeled with a certain predefined class. All the observations combined with their class labels are known as adata set. When a new observation is received, that observation is classified based on previous experience.[44] There are many kinds of classifiers in use.[98]Thedecision treeis the simplest and most widely used symbolic machine learning algorithm.[99]K-nearest neighboralgorithm was the most widely used analogical AI until the mid-1990s, andKernel methodssuch as thesupport vector machine(SVM) displaced k-nearest neighbor in the 1990s.[100]Thenaive Bayes classifieris reportedly the "most widely used learner"[101]at Google, due in part to its scalability.[102]Neural networksare also used as classifiers.[103] An artificial neural network is based on a collection of nodes also known asartificial neurons, which loosely model theneuronsin a biological brain. It is trained to recognise patterns; once trained, it can recognise those patterns in fresh data. There is an input, at least one hidden layer of nodes and an output. Each node applies a function and once theweightcrosses its specified threshold, the data is transmitted to the next layer. A network is typically called a deep neural network if it has at least 2 hidden layers.[103] Learning algorithms for neural networks uselocal searchto choose the weights that will get the right output for each input during training. The most common training technique is thebackpropagationalgorithm.[104]Neural networks learn to model complex relationships between inputs and outputs andfind patternsin data. In theory, a neural network can learn any function.[105] Infeedforward neural networksthe signal passes in only one direction.[106]The termperceptrontypically refers to a single-layer neural network.[107]In contrast, deep learning uses many layers.[108]Recurrent neural networks(RNNs) feed the output signal back into the input, which allows short-term memories of previous input events.Long short-term memorynetworks (LSTMs) are recurrent neural networks that better preserve longterm dependencies and are less sensitive to thevanishing gradient problem.[109]Convolutional neural networks(CNNs) use layers ofkernelsto more efficiently process local patterns. This local processing is especially important inimage processing, where the early CNN layers typically identify simple local patterns such as edges and curves, with subsequent layers detecting more complex patterns like textures, and eventually whole objects.[110] Deep learninguses several layers of neurons between the network's inputs and outputs.[108]The multiple layers can progressively extract higher-level features from the raw input. For example, inimage processing, lower layers may identify edges, while higher layers may identify the concepts relevant to a human such as digits, letters, or faces.[112] Deep learning has profoundly improved the performance of programs in many important subfields of artificial intelligence, includingcomputer vision,speech recognition,natural language processing,image classification,[113]and others. The reason that deep learning performs so well in so many applications is not known as of 2021.[114]The sudden success of deep learning in 2012–2015 did not occur because of some new discovery or theoretical breakthrough (deep neural networks and backpropagation had been described by many people, as far back as the 1950s)[i]but because of two factors: the incredible increase in computer power (including the hundred-fold increase in speed by switching toGPUs) and the availability of vast amounts of training data, especially the giantcurated datasetsused for benchmark testing, such asImageNet.[j] Generative pre-trained transformers(GPT) arelarge language models(LLMs) that generate text based on the semantic relationships between words in sentences. Text-based GPT models are pre-trained on a largecorpu

## 5. verify new token column

In [39]:
df[['Text', 'tokens']].head()

,Text,tokens
0,Artificial intelligence(AI) is the capability...,"[Artificial, intelligence, (, AI, ), is, the, ..."
1,Machine learning(ML) is a field of study inar...,"[Machine, learning, (, ML, ), is, a, field, of..."
2,"Inmachine learning,deep learning(DL) focuses o...","[Inmachine, learning, ,, deep, learning, (, DL..."
3,Aneural networkis a group of interconnected un...,"[Aneural, networkis, a, group, of, interconnec..."
4,Computer visiontasks include methods foracquir...,"[Computer, visiontasks, include, methods, fora..."

## 6. First 20 tokens of one Text

In [40]:
first_20_tokens = df['tokens'].iloc[0][:20]
print(first_20_tokens)

['Artificial', 'intelligence', '(', 'AI', ')', 'is', 'the', 'capability', 'ofcomputational', 'systemsto', 'perform', 'tasks', 'typically', 'associated', 'withhuman', 'intelligence', ',', 'such', 'aslearning', ',']

## Step 2: Remove Stopwords

- Remove common words like "the", "is", "and"
- show: Stopword list
- Average number of words removed

## 1.Download & import stopwords

In [41]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

## 2.creating stopword list

In [42]:
stop_words = set(stopwords.words('english'))
print(list(stop_words)[:20])

['ours', 'yours', 'below', 'with', 'once', 'down', 'through', 'hasn', 'mightn', 'ourselves', 'at', 'between', 'm', 'to', "it'll", 'mustn', 'weren', "couldn't", 'out', 'nor']

## 3.Removing stopwords from tokens

In [43]:
df['tokens_no_stopwords'] = df['tokens'].apply(
    lambda tokens: [word for word in tokens
                    if word.lower() not in stop_words]
)

## 4.Before & after tokens

In [50]:
print("original tokens:", df['tokens'] [0][:20])
print("After removing stopwords:", df['tokens_no_stopwords'] [0][:20])

original tokens: ['Artificial', 'intelligence', '(', 'AI', ')', 'is', 'the', 'capability', 'ofcomputational', 'systemsto', 'perform', 'tasks', 'typically', 'associated', 'withhuman', 'intelligence', ',', 'such', 'aslearning', ',']
After removing stopwords: ['Artificial', 'intelligence', '(', 'AI', ')', 'capability', 'ofcomputational', 'systemsto', 'perform', 'tasks', 'typically', 'associated', 'withhuman', 'intelligence', ',', 'aslearning', ',', 'reasoning', ',', 'problem-solving']

## 5.total no of words removed per article

In [51]:
df['words_removed'] = df['tokens'].apply(len) - df['tokens_no_stopwords'].apply(len)

In [52]:
print(df['words_removed'].head())

0    4385
1    2845
2    2490
3     227
4    1353
Name: words_removed, dtype: int64

## 6. Average number of words removed

In [54]:
avg_words_removed = df['words_removed'].mean()
print("Average number of words removed:", round (avg_words_removed,2))

Average number of words removed: 2867.28

In [55]:
df[['tokens', 'tokens_no_stopwords', 'words_removed']].head()

,tokens,tokens_no_stopwords,words_removed
0,"[Artificial, intelligence, (, AI, ), is, the, ...","[Artificial, intelligence, (, AI, ), capabilit...",4385
1,"[Machine, learning, (, ML, ), is, a, field, of...","[Machine, learning, (, ML, ), field, study, in...",2845
2,"[Inmachine, learning, ,, deep, learning, (, DL...","[Inmachine, learning, ,, deep, learning, (, DL...",2490
3,"[Aneural, networkis, a, group, of, interconnec...","[Aneural, networkis, group, interconnected, un...",227
4,"[Computer, visiontasks, include, methods, fora...","[Computer, visiontasks, include, methods, fora...",1353

## Step 3: Stemming vs Lemmatization

## Apply both:
- Stemming (PorterStemmer)
- Lemmatization (WordNetLemmatizer)
## Create:
- tokens_stemmed
- tokens_lemmatized
## Compare results on 10 words
## Answer: Which method is better and why?

## 1.Importing libraries

In [56]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

from nltk.stem import PorterStemmer, WordNetLemmatizer

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

## 2.Initialize stemmer and lemmatizer

In [57]:
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

## 3.create new columns

In [58]:
df['tokens_stemmed'] = df['tokens_no_stopwords'].apply(
    lambda tokens: [stemmer.stem(word) for word in tokens]
)

df['tokens_lemmatized'] = df['tokens_no_stopwords'].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

## 4. Compare results on 10 words

In [60]:
sample_words = df['tokens_no_stopwords'].iloc[0][:10]

comparison = []

for word in sample_words:
    comparison.append([
        word,
        stemmer.stem(word),
        lemmatizer.lemmatize(word)
    ])

for original, stemmed, lemmatized in comparison:
    print(f"{original:15} {stemmed:15} {lemmatized}")

Artificial      artifici        Artificial
intelligence    intellig        intelligence
(               (               (
AI              ai              AI
)               )               )
capability      capabl          capability
ofcomputational ofcomput        ofcomputational
systemsto       systemsto       systemsto
perform         perform         perform
tasks           task            task

## 5.view result

In [61]:
df[['tokens_no_stopwords',
    'tokens_stemmed',
    'tokens_lemmatized']].head()

,tokens_no_stopwords,tokens_stemmed,tokens_lemmatized
0,"[Artificial, intelligence, (, AI, ), capabilit...","[artifici, intellig, (, ai, ), capabl, ofcompu...","[Artificial, intelligence, (, AI, ), capabilit..."
1,"[Machine, learning, (, ML, ), field, study, in...","[machin, learn, (, ml, ), field, studi, inarti...","[Machine, learning, (, ML, ), field, study, in..."
2,"[Inmachine, learning, ,, deep, learning, (, DL...","[inmachin, learn, ,, deep, learn, (, dl, ), fo...","[Inmachine, learning, ,, deep, learning, (, DL..."
3,"[Aneural, networkis, group, interconnected, un...","[aneur, networki, group, interconnect, unit, c...","[Aneural, networkis, group, interconnected, un..."
4,"[Computer, visiontasks, include, methods, fora...","[comput, visiontask, includ, method, foracquir...","[Computer, visiontasks, include, method, forac..."

## Which method is better and why?
- Lemmatization is generally better for NLP tasks because:
- Lemmatization converts words to their actual base form. e.g. running → run
- gives meaningful words
- Gives more accuracy.
- stemming : stemming is faster but sometimes it creates incomplete words.
- use stemming when speed is imp and use lemmatization for NLP tasks

## Step 4: Final Text
-  Join cleaned tokens back into text
-  Create final column: clean_text

In [62]:
df['clean_text'] = df['tokens_no_stopwords'].apply(lambda x: " ".join(x))

In [63]:
print(df['clean_text'].head())

0    Artificial intelligence ( AI ) capability ofco...
1    Machine learning ( ML ) field study inartifici...
2    Inmachine learning , deep learning ( DL ) focu...
3    Aneural networkis group interconnected units c...
4    Computer visiontasks include methods foracquir...
Name: clean_text, dtype: object

## Part4 : Convert Text to Numbers (TF-IDF)

- Split data: 80% train / 20% test
- Use TfidfVectorizer
## Steps:
- Fit only on training data
- Transform both train and test
## Show:
- Shape of TF-IDF matrix
- Top 15 important words per category

## 1.train-test-split

In [65]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df['clean_text'],
    df['Label'],
    test_size=0.2,
    random_state=42,
    stratify=df['Label']
)

## 2.TF-IDF Vectorization

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

## 3. shape of TF-IDF Matrix

In [67]:
print("Train TF-IDF shape:", X_train_tfidf.shape)
print("Test TF-IDF shape:", X_test_tfidf.shape)

Train TF-IDF shape: (48, 41332)
Test TF-IDF shape: (12, 41332)

## 4.get word names

In [68]:
feature_names = vectorizer.get_feature_names_out()

## 5. Top 15 imp words per category

In [71]:
import numpy as np

y_train = np.array(y_train)
categories = np.unique(y_train)

for category in categories:
    idx = (y_train == category)   # now it's a numpy boolean array
    
    mean_tfidf = X_train_tfidf[idx].mean(axis=0).A1
    
    top_indices = mean_tfidf.argsort()[-15:][::-1]
    top_words = [feature_names[i] for i in top_indices]
    
    print("Top words for category:", category)
    print(top_words)

Top words for category: AI
['ai', 'learning', 'data', 'speech', 'machine', 'neural', 'robots', 'chatbots', 'agi', 'recognition', 'generative', 'used', 'computer', 'vision', 'mining']
Top words for category: Climate
['climate', 'carbon', 'emissions', 'warming', 'energy', 'global', 'change', 'environmental', 'sustainability', 'dioxide', 'deforestation', 'sea', 'agreement', 'temperature', 'greenhouse']
Top words for category: History
['empire', 'war', 'ottoman', 'century', 'soviet', 'dynasty', 'roman', 'western', 'period', 'bc', 'germany', 'german', 'bce', 'british', 'europe']
Top words for category: Space
['space', 'nasa', 'mars', 'moon', 'earth', 'mission', 'telescope', 'spacecraft', 'satellites', 'orbit', 'launch', 'spacex', 'lunar', 'first', 'hubble']

## Part 5 — Save and Explain
## Save these files:
- raw_dataset.csv
- cleaned_dataset.csv
- final_dataset.csv (with clean_text + label + stats)

## 1.save raw data - original data

In [73]:
df.to_csv("raw_dataset.csv", index=False)
print("Dataset Saved")

Dataset Saved

## 2.Save cleaned dataset - tokens, tokens_no_stopwords

In [74]:
cleaned_df = df[['Text', 'Label', 'tokens', 'tokens_no_stopwords']]
cleaned_df.to_csv("cleaned_dataset.csv", index=False)

## 3.final dataset

In [75]:
df['token_count'] = df['tokens'].apply(len)

df['clean_token_count'] = df['tokens_no_stopwords'].apply(len)

df['words_removed'] = df['token_count'] - df['clean_token_count']

final_df = df[['clean_text', 'Label', 'token_count', 'clean_token_count', 'words_removed']]

final_df.to_csv("final_dataset.csv", index=False)

In [76]:
test = pd.read_csv("final_dataset.csv")
print(test.head())

                                          clean_text Label  token_count  \
0  Artificial intelligence ( AI ) capability ofco...    AI        15282
1  Machine learning ( ML ) field study inartifici...    AI         9705
2  Inmachine learning , deep learning ( DL ) focu...    AI         9729
3  Aneural networkis group interconnected units c...    AI          773
4  Computer visiontasks include methods foracquir...    AI         4253

   clean_token_count  words_removed
0              10897           4385
1               6860           2845
2               7239           2490
3                546            227
4               2900           1353

## explanation:  
- This project focused on building a complete text classification pipeline using Natural Language Processing (NLP). The main problem I solved was converting raw, unstructured text data into a clean and structured format that could be used for machine learning. The workflow included web data collection, text cleaning (removing HTML tags, punctuation, stopwords), tokenization, and feature engineering. Finally, I converted the cleaned text into numerical features using TF-IDF and prepared it for classification tasks.

- One interesting insight from the dataset was how much information is lost during preprocessing. While cleaning the text made it more suitable for machine learning, it also reduced the number of words significantly. For example, in many cases nearly 30–50% of words were removed as stopwords or irrelevant symbols. Despite this reduction, the remaining words were still strong enough to represent the meaning of the text effectively.

- One surprising thing I learned was how powerful simple techniques like TF-IDF can be. Even without using advanced deep learning models, TF-IDF was able to clearly highlight important words for each category. It showed that words with high frequency in a category but low frequency across others carry strong predictive power. Another surprise was how sensitive models are to preprocessing steps—small changes in cleaning or tokenization can significantly affect results.

- Overall, this project helped me understand the full NLP pipeline from raw text to model-ready data and gave me practical experience in text preprocessing, feature extraction, and dataset preparation for machine learning.